name: CI

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Wayland build dependencies
        run: sudo apt-get update && sudo apt-get install --yes libwayland-dev libxkbcommon-dev
      - name: Install stable Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add clippy rustfmt
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace
      - name: Build
        run: cargo build --workspace
